zk:
  image: bobrik/zookeeper
  net: host
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: " 1"

master:
  image: mesosphere/mesos-master:0.28.1-2.0.20.ubuntu1404
  net: host
  environment:
    MESOS_ZK: zk://${DOCKER_IP}:2181/mesos
    MESOS_HOSTNAME: ${DOCKER_IP}
    MESOS_IP: ${DOCKER_IP}
    MESOS_QUORUM: "1"
    MESOS_CLUSTER: local-mesos
    MESOS_PORT: 5050
    MESOS_WORK_DIR: /var/lib/mesos/master
    MESOS_LOG_DIR: /var/log/mesos/master

slave:
  image: mesosphere/mesos-slave:0.28.1-2.0.20.ubuntu1404
  net: host
  privileged: true
  environment:
    MESOS_MASTER: zk://${DOCKER_IP}:2181/mesos
    MESOS_DOCKER_SOCK: /var/run/docker.sock
    MESOS_ISOLATOR: cgroups/cpu,cgroups/mem
    MESOS_HOSTNAME: ${DOCKER_IP}
    MESOS_IP: ${DOCKER_IP}
    MESOS_LOG_DIR: /var/log/mesos/slave
    MESOS_WORK_DIR: /var/lib/mesos/master
    MESOS_PORT: 5051
    MESOS_CONTAINERIZERS: docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro
    - /proc:/host/proc:ro

marathon:
  image: mesosphere/marathon:v1.1.1
  net: host
  environment:
    MARATHON_MASTER: zk://${DOCKER_IP}:2181/mesos
    MARATHON_ZK: zk://${DOCKER_IP}:2181/marathon
    MARATHON_HOSTNAME: ${DOCKER_IP}
  command: --event_subscriber http_callback

traefik:
  image: traefik
  command: --web --web.address=":8088" --docker --docker.domain=docker.localhost --marathon --marathon.endpoint="http://${DOCKER_IP}:8080" --marathon.domain="marathon.locahost" --logLevel=DEBUG
  ports:
    - "80:80"
    - "8088:8088"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"